---
- name: |
    Install cri-o runtime and Kubernetes tools on Ubuntu hosts and pre-bootstrap a k8s cluster
  hosts: all
  become: true
  roles:
    - role: crio
    - role: k8s_tools
    - role: pre_bootstrap
